<?php

/**
 * M report - tool for creating outputs based on SQL select query in different formats
 */
class Mreport{
  var $settings;
  
  /**
   * Konstruktor
   * @param array $settings - in array pragma there is an optional setting for cloumn behavoir - Aliases 
   *  and sizes, colors (for XLS sheet)
   */
  function __construct($settings){
    $this->settings=$settings;
    if (!isset($this->settings['name'])) $this->settings['name']='report';
    if (!isset($this->settings['sheet_name'])) $this->settings['sheet_name']=$this->settings['name'];
  }

  /** Executive of create export file
   * @param string $a - data generated by SqlFetchtarray method
   * @param string $typ - type of file (csv,xls)
   */
  function export_file($a,$typ='csv',$settings=[]){
    if ($typ=='csv') $this->export_csv($a);
    elseif ($typ=='xls') $this->export_xls($a,$settings);
  }
  
  /** private method for export to csv
   * @param array $a - data array to export
   */
  private function export_csv($a){
    $s='';
    $sepa=';';
    $nadpisy=array_keys($a[0]);
    $polozky=array_keys($a[0]);
    for($i=0;$i<count($nadpisy);$i++){
      $s.=gl(strtoupper($nadpisy[$i]),$i<count($nadpisy)-1?$sepa:'');
    }
    $s.="\n";
    for($nn=0;$nn<count($a);$nn++){
      $D=$a[$nn];
      for($i=0;$i<count($polozky);$i++){
        $pom=str_replace('"','\'',str_replace("\r",' ',str_replace("\n",' ',$D[$polozky[$i]])));
        $pom='"'.$pom.'"';
        $s.=gl($pom,$i<count($polozky)-1?$sepa:'');
      }
      $s.="\n";
    }
    header('Content-Type: text/plain;charset=UTF-8'); 
    header('Content-Disposition: attachment;filename="'.
     $this->settings['name'].'_'.date('dmy_hi').'.csv"');
    header('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT'); // always modified
    header('Cache-Control: cache, must-revalidate'); // HTTP/1.1
    header('Pragma: public');  
    if (isset($this->settings['win1250']) && $this->settings['win1250']) $s=iconv("utf-8//TRANSLIT","windows-1250",$s);
    echo $s;    
  }

  /** private method for export to xls sheet
   * @param array $a - data array to export
   * depends on setting the M5_EXCEL_VENDOR constant - it contains the location of PHPExcel library
   */
  private function export_xls($a,$settings){
    require_once M5_EXCEL_VENDOR.'PHPExcel.php';
    
    $excel = new PHPExcel();
    
    /* Set document properties */
    $excel->getProperties()->setCreator("CGS Aplikace M5")
     ->setLastModifiedBy("TerDok")
     ->setTitle("Office 2007 XLSX Test Document")
     ->setSubject("Office 2007 XLSX Test Document")
     ->setDescription("Export geological data")
     ->setKeywords("CGS geology")
     ->setCategory("Output database data");
    $ex=$excel->setActiveSheetIndex(0);
    
    /* nadpis prvni radek */
    $ke=array_keys($a[0]); 
    $kn=$ke; /* pripadne modifikace pro popisky sloupcu, tech, ktere byly uvedeny */
    $co=count($ke);
    if (isset($settings['pragma'])){
      $p=$settings['pragma'];
      for($i=0;$i<count($p);$i++){
        if ($settings['pragma'][$i]['name']==$ke[$i] && isset($settings['pragma'][$i]['comment'])){
          $kn[$i]=$settings['pragma'][$i]['comment'];
        }
      }
    }

    for($m=0;$m<$co;$m++){
      $ex->setCellValue($this->pismeno($m+1).'1', $kn[$m]);
      
      if (isset($settings['pragma'][$m]['size'])){
        $ex->getColumnDimension($this->pismeno($m+1))->setWidth($settings['pragma'][$m]['size']);
      }
      $ex->getStyle($this->pismeno($m+1).'1')->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID);
      $ex->getStyle($this->pismeno($m+1).'1')->getFill()->getStartColor()->setRGB('CCCCCC');
        
    }

    /* datovy obsah */
    for($n=0;$n<count($a);$n++){
      for($m=0;$m<$co;$m++){
        $ex->setCellValue($this->pismeno($m+1).($n+2), $a[$n][$ke[$m]] ); 
        if (isset($settings['pragma'][$m]['color'])){
          $ex->getStyle($this->pismeno($m+1).($n+2))->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID);
          $ex->getStyle($this->pismeno($m+1).($n+2))->getFill()->getStartColor()->setRGB($settings['pragma'][$m]['color']);
        }
      }  
    }
    
    /* popiska listu */
    $excel->getActiveSheet()->setTitle($this->settings['sheet_name']);
    $excel->setActiveSheetIndex(0);
    
    /* odeslani souboru: header + save method */
    header('Content-Type: application/vnd.ms-excel');
    header('Content-Disposition: attachment;filename="'.$this->settings['name'].'_'.date('dmy_hi').'.xls"');
    header('Cache-Control: max-age=0');
    // If you're serving to IE 9, then the following may be needed
    //header('Cache-Control: max-age=1');
    // If you're serving to IE over SSL, then the following may be needed
    header('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT'); // always modified
    header('Cache-Control: cache, must-revalidate'); // HTTP/1.1
    header('Pragma: public'); // HTTP/1.0
    $objWriter = PHPExcel_IOFactory::createWriter($excel, 'Excel5');
    $objWriter->save('php://output');
  }
  
  /**
   * vraci pismeny kod n-teho sloupce 1=A,2=B,...,27=AA,28=AB atd..
   * @param int $n - cislo sloupce
   * @return string - pismeny kod
   */
  private function pismeno($n){
    $k=ord('A')-1;
    if ($n>26){
      return chr(floor($n/26)+$k).chr($n%26+$k);
    }else{
      return chr($n+$k);
    }
  }   
  

}
?>